import esbuild from "esbuild-wasm";
import { spawnSync } from "node:child_process";
import { builtinModules } from "node:module";
import { dirname, join } from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const prod = process.argv.includes("production");
const watch = process.argv.includes("--watch");

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
If you want to view the source, please visit the src folder.
*/`;

const external = [
  "obsidian",
  "electron",
  "@codemirror/autocomplete",
  "@codemirror/collab",
  "@codemirror/commands",
  "@codemirror/language",
  "@codemirror/lint",
  "@codemirror/search",
  "@codemirror/state",
  "@codemirror/view",
  "@lezer/common",
  "@lezer/highlight",
  "@lezer/lr",
  ...builtinModules,
  ...builtinModules.map((moduleName) => `node:${moduleName}`)
];

const buildOptions = {
  banner: {
    js: banner
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external,
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod
};

function runCliFallback() {
  const pluginDir = dirname(fileURLToPath(import.meta.url));
  const cliPath = join(pluginDir, "node_modules", "esbuild-wasm", "bin", "esbuild");
  const args = [
    ...buildOptions.entryPoints,
    "--bundle",
    `--format=${buildOptions.format}`,
    `--target=${buildOptions.target}`,
    `--log-level=${buildOptions.logLevel}`,
    `--outfile=${buildOptions.outfile}`,
    "--tree-shaking=true",
    `--banner:js=${banner}`,
    ...external.map((entry) => `--external:${entry}`)
  ];

  if (buildOptions.minify) {
    args.push("--minify");
  }

  if (buildOptions.sourcemap) {
    args.push(`--sourcemap=${buildOptions.sourcemap}`);
  }

  if (watch) {
    args.push("--watch");
  }

  const result = spawnSync(process.execPath, [cliPath, ...args], {
    stdio: "inherit",
    cwd: pluginDir
  });

  if (result.error) {
    throw result.error;
  }

  if (typeof result.status === "number" && result.status !== 0) {
    process.exit(result.status);
  }
}

if (watch) {
  try {
    const context = await esbuild.context(buildOptions);
    await context.watch();
    console.log("Watching Contex Agent plugin files...");
  } catch (error) {
    console.warn("esbuild-wasm service unavailable; falling back to CLI watch.");
    runCliFallback();
  }
} else {
  try {
    await esbuild.build(buildOptions);
  } catch (error) {
    if (error?.code !== "EPERM") {
      throw error;
    }

    console.warn("esbuild-wasm service unavailable; falling back to CLI build.");
    runCliFallback();
  }
}
